### PR TITLE
Added felt-pen to benchmark & Added nonce for more realistic benchmarking

### PR DESCRIPTION
**Pull request by nin-jin**
```
colorette × 287 525 ops/sec
chalk × 158 869 ops/sec
kleur × 183 174 ops/sec
colors × 85 787 ops/sec
ansi-colors × 122 483 ops/sec
felt-pen × 254 073 ops/sec
```

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Have you finished adding tests to `felt-pen`? Feel free to grab our [tests](https://github.com/jorgebucaran/colorette/tree/main/tests) if you like.

**Comment by nin-jin** [comment]
Yep, I have finished testing.

**Comment by kibertoad** [comment]
@nin-jin What Jorge means is that your project doesn't have any unit tests, just scripts for local execution, that would still not fail CI in case it didn't color anything.

**Comment by nin-jin** [comment]
Yes, there is nothing to check on CI here. Whether there will be a coloring and which one depends solely on the behavior of the TTY. Everything is colored on the TTY available to me, which means that the correct codes are generated. Unit tests cannot check this in principle.

**Comment by kibertoad** [comment]
@nin-jin Please check https://github.com/jorgebucaran/colorette/tree/main/tests as an example of what kind of useful tests there could be, to validate that colours are generated correctly.

**Comment by nin-jin** [comment]
It's useless tests and tests of functionality which my implementation doesn't support by design. In any case, the question of testing does not relevant to the topic of this pr.

**Comment by jorgebucaran** [comment]
I suggest adding tests for the following reasons: CI integration, avoiding regressions, and making sure we are comparing apples to apples. I don't fully understand what's going on [here](https://github.com/nin-jin/felt-pen/blob/0d4717a0264adb53ea776705787b3f637580e826/index.mjs#L42-L48), but I confess I haven't had much time to look into it.

**Comment by nin-jin** [comment]
If you are concerned about the correctness of the comparison, then write exhaustive tests for the benchmark and require that each implementation corresponds to them. From the fact that I will have a dozen meaningless tests, as in other libraries, there is no guarantee that all produce a single result.

You can read my following articles if you doubt that I understand a little about testing, and am able to soberly assess when and which tests should be written, and when and which do not make sense, when it is worth writing automatic tests, and when it is necessary to check the behavior on real TTY.

- [Fractal Testing](https://github-com.translate.goog/nin-jin/slides/tree/master/testing?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=nui)
- [TDD Deconstruction](https://github-com.translate.goog/nin-jin/slides/tree/master/abbr?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=nui)
- [Automated Testing Concepts](https://github-com.translate.goog/nin-jin/HabHub/issues/12?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=nui)

So let's leave the question of completeness and quality of automatic testing on the conscience of the maintainer, and not tell that the composition of two functions is difficult to understand and can lead to regression.

**Comment by jorgebucaran** [comment]
I don't doubt you. Thank you for sharing your articles. They seem fun and original. 

Could you meet us in the middle? How about adding tests only for the color nesting feature?

**Comment by jorgebucaran** [comment]
Thank you for sharing your articles. They seem like an interesting read.  

Maybe you can meet us in the middle? How about adding tests only for the color nesting feature?

**Comment by ai** [comment]
@jorgebucaran I think https://github.com/jorgebucaran/colorette/commit/6a4a871e5953e8538c2a606eb62b9c1d664ad284 will be better on adding explicit link to `chalk` and `picocolors`’s mention and link.

**Pull request closed without merging**
