### PR TITLE
Fix Vite support

### LINKED ISSUE #89: SvelteKit + colorette
I get error in browser: "process is not defined"
I think the reason is in Vite and its handling of environment variables.

Similar problem:

https://stackoverflow.com/questions/71083110/vue-uncaught-referenceerror-process-is-not-defined

### PR DESCRIPTION
**Pull request by kibertoad**
fix #89

### CODE REVIEW

**Comment by kibertoad** [comment]
@jaclas Can you check if this branch fixes your issue?

**Comment by jaclas** [comment]
I checked, everything works, thank you very much!

**Comment by jorgebucaran** [comment]
Thank you, @jaclas. Just curious, but how did you test that this branch fixed your issue?

**Comment by jaclas** [comment]
> 
@jorgebucaran  Damn... I installed colorette with npm, did a quick test, saw the color changes in the console (bash) and wrote that it was ok. Sorry for the rush, didn't want to block the issue and hence too superficial check.

**Comment by jorgebucaran** [comment]
Okay, so are we positive that this fixes the Vite issue? Just want to make sure.

**Comment by jaclas** [comment]
Unfortunately not, I modified the code bundled about by Vite for the latest changes from Colorrette and there is still an error:

obraz

**Comment by kibertoad** [comment]
@jaclas Can you try solution from https://github.com/facebook/create-react-app/issues/12212 and report back if it helps?

Namely adding
```
if (!('process' in window)) {
  // @ts-ignore
  window.process = {}
}
```
into the beginning of the file

**Comment by jaclas** [comment]
It helped, the error is no longer there:

obraz

**Comment by kibertoad** [comment]
@jorgebucaran I don't think it's possible to have version that works both with Node and with browser, and also is an ESM module (because that one executes in strict mode and does not allow undefined variables). How would you like to proceed?

**Comment by jorgebucaran** [comment]
Would `import process from "node:process"` help? 

Can anybody help me understand how browser support should work? How do you use this package in a browser? And what is the expected behavior (other than not seeing an uncaught error)?

**Comment by kibertoad** [comment]
No, because it is failing in non-node environments where node package is not going to be present either.
Not sure where it is used in browser, I assume some of the deps are colouring their console with colorette, hence things break down.
Fixing support universally would require making colorette a CJS module (so that it no longer crashes on referencing undeclared variables)

**Comment by jorgebucaran** [comment]
Hmm, would this not work either? 🤔 

```js
const proc = typeof process === "undefined" ? {} : process
```

**Comment by jorgebucaran** [comment]
Hmm, this good? 🤔 

```js
const proc = typeof process === "undefined" ? {} : process
```

**Comment by kibertoad** [comment]
@jorgebucaran I think any reference to non-defined variable will break it. you can try running locally and replace process with xyz

**Comment by jaclas** [comment]
I am using colorette in a backend project in node. There I made my own wrapper for a logger that also uses colorette. Now I started working in SvelteKit and just wanted to move my logger wrapper to that environment, unfortunately I ran into a problem and had to abandon colorette. SvelteKit works on both sides, the backend and the frontend, in the backend everything colors nicely (I like it a lot), and already in the browser it would be enough if it didn't crash, I don't know if the colors are even available in the browser console.

**Comment by jorgebucaran** [comment]
Thanks for the info, @jaclas. 👍 

@kibertoad https://github.com/jorgebucaran/colorette/pull/92#issuecomment-1146896484 seems to work for me.

**Comment by jaclas** [comment]
@kibertoad Okay, just give me a hint how should I install this version? Should I clone your  repo or is it possible via npm?

**Comment by jaclas** [comment]
Thx for tip with npm. It will come in handy on other occasions.
I have now copied the file as you advised and it seems to be ok:

obraz

**Comment by kibertoad** [comment]
@jaclas Thank you for checking this!
@jorgebucaran We are good to merge then :)

**Review by jorgebucaran — APPROVED** [review]

**Comment by so1ve** [comment]
@jaclas Actually you can use define:

```ts
export default defineConfig({
  define: {
    'process.env': {}
  }
})
```

**Pull request merged**
