### PR TITLE
Add ESM support

### PR DESCRIPTION
**Pull request by ai**
This PR adds ES modules support to colorette. Closes https://github.com/jorgebucaran/colorette/issues/39.

Right now you can’t import functions from colorette in Node.js native ES modules:

```js
// node -v => v14.4.0

import { bold } from 'colorette'
/*       ^^^^
SyntaxError: The requested module 'colorette' is expected to be of type CommonJS, which does not support named exports. 
CommonJS modules can be imported by importing the default export. */
```

To avoid code duplication, I added [`dual-publish`](https://github.com/ai/dual-publish/) tool. You need to call `npx dual-publish` instead of `npm publish`:

1. Copy the project to a temporary directory.
1. It will copy `index.js` to `index.cjs`
2. It will convert `index.js` to ESM
3. It will add the `exports` section to `package.json`
4. Also, it will clean `package.json` from `devDependencies` and development `scripts`.
5. Release the project from this temporary directory to npm.

Benefits of using `dual-publish`:

1. It is used in around [90 npm packages](https://github.com/search?q=%22dual-publish%22&type=Code).
2. I tested it in `nanoid` with [9M downloads](https://npm-stat.com/charts.html?package=nanoid).
3. It has [integration tests](https://github.com/ai/dual-publish/blob/master/test/index.test.js) to be sure, that it works well in a big variety of use cases: Node.js, TypeScript, ts-node, webpack, Rollup, Parcel, React Native
4. It uses `colorette` inside 😸

You can check the tool by calling `npx dual-publish --check`. It will put built to `dual-publish-tmp` without releasing it to npm.

```
$ npx dual-publish --check  
Check npm package content in ./dual-publish-tmp/

$ tree ./dual-publish-tmp/
./dual-publish-tmp/
├── bench // <= this directory will be ignored during the publishing
│   ├── index.js
│   └── package.json
├── colorette.d.ts
├── index.cjs
├── index.js
├── LICENSE.md
├── package.json
└── README.md

1 directory, 8 files

$ cat dual-publish-tmp/index.js 
"use strict"

let enabled =
  !("NO_COLOR" in process.env) &&
  ("FORCE_COLOR" in process.env ||
    process.platform === "win32" ||
    (process.stdout != null &&
      process.stdout.isTTY &&
      process.env.TERM &&
      process.env.TERM !== "dumb"))

const raw = (open, close, searchRegex, replaceValue) => (s) =>
  enabled
    ? open +
      (~(s += "").indexOf(close, 4) // skip opening \x1b[
        ? s.replace(searchRegex, replaceValue)
        : s) +
      close
    : s

const init = (open, close) => {
  return raw(
    `\x1b[${open}m`,
    `\x1b[${close}m`,
    new RegExp(`\\x1b\\[${close}m`, "g"),
    `\x1b[${open}m`
  )
}

const options = Object.defineProperty({}, "enabled", {
  get: () => enabled,
  set: (value) => (enabled = value),
})
const reset = init(0, 0)
const bold = raw("\x1b[1m", "\x1b[22m", /\x1b\[22m/g, "\x1b[22m\x1b[1m")
const dim = raw("\x1b[2m", "\x1b[22m", /\x1b\[22m/g, "\x1b[22m\x1b[2m")
const italic = init(3, 23)
…

export {
  options,
  reset,
  bold,
  dim,
  italic,
  …
}

$ cat dual-publish-tmp/package.json 
{
  "name": "colorette",
  "version": "1.2.0",
  "description": "Color your terminal using pure idiomatic JavaScript.",
  "main": "index.cjs",
  "types": "colorette.d.ts",
  "repository": {
    "type": "git",
    "url": "jorgebucaran/colorette"
  },
  "files": [
    "index.js",
    "colorette.d.ts"
  ],
  "keywords": [
    "colorette",
    "terminal",
    "styles",
    "color",
    "ansi"
  ],
  "author": "Jorge Bucaran",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/jorgebucaran/colorette/issues"
  },
  "homepage": "https://github.com/jorgebucaran/colorette",
  "type": "module",
  "module": "index.js",
  "react-native": "index.js",
  "exports": {
    "./package.json": "./package.json", // <= this line is required by React Native
    ".": {
      "require": "./index.cjs",
      "import": "./index.js"
    }
  }
}
```

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Thank you, @ai. Do you think we can use this for a while (how long I don't know, months? years?) until we can completely drop CJS support? What's your own Node.js support plan/schedule? Are you going to publish dual modules for the foreseeable future or going to pull the plug on CJS for a few selected modules?

**Comment by ai** [comment]
> Do you think we can use this for a while (how long I don't know, months? years?) until we can completely drop CJS support? What's your own Node.js support plan/schedule?

In my modules, I am supporting all [Maintenance LTS](https://nodejs.org/en/about/releases/) Node.js version.

So I will support CJS/ESM in my modules (and will support `dual-publish`) until 2021-04-30 or 2022-04-30 (depends on how good Node.js 12 works with ESM-only modules).

Right now `dual-publish`’s packages should have CJS in repo (because Jest had problems with ESM). But at some moment I will move to “ESM→CJS” compiling (now we have CJS→ESM compiling). It will simplify `dual-publish` dropping when we have ESM support everywhere.

**Comment by jorgebucaran** [comment]
Sounds like a good plan. 2021-04-30 is still far ahead, but not that far. 👍

**Comment by jorgebucaran** [comment]
@ai I wouldn't mind duplicating the code for now at all, after all, it's just a temporary solution. But maybe you can add a script to package.json `dual-release` or so to simplify the special release process.

**Comment by ai** [comment]
I personally a calling `npx dual-publish` during the releases because:

1. It is avoiding all DRY issues like forgetting to backport fixes to the `.cjs` file.
2. I am constantly improving `dual-publish` (for instance, recently webpack team [came](https://github.com/ai/dual-publish/issues/10) this fixes for webpack 5). Updating the tool is better that keep tracking all new best practices for dual packages.
3. `dual-publish` also cleans `package.json` from development configs.

But I understand that come of these reasons could be not important for other projects. I can change PR by calling `npx dual-publish --check` and then copying converted files to the PR.

**Comment by jorgebucaran** [comment]
@ai There may be other options, but here are the first 3 that come to mind:

1) Duplicate the code. Easy and simple. It's temporary after all.
2) Use `dual-publish`. More robust. If we go this route, I'd like to add a npm script to do everything for me (or is `npx dual-publish` enough?)
3) Support ESM. Drop CJS. Go Bold.

Thoughts?

**Comment by ai** [comment]
> Support ESM. Drop CJS. Go Bold.

Only the latest Node.js 14 has good ESM support. It is still not the most popular Node.js version.

Also, most of Node.js projects (like my Autoprefixer, which were switched to `colorette` recently) need to support all maintained LTS versions of Node.js. Dropping Node.js 10 and 12 support will not allow using your awesome library for many developers.

> Duplicate the code. Easy and simple. It's temporary after all.
> Use dual-publish. More robust.

Yeap. I think there are 2 main options.

> I'd like to add a npm script to do everything for me (or is npx dual-publish enough?)

Oops. I forgot to change the `publish` script. Fixed 2f7992b

**Comment by jorgebucaran** [comment]
I'm going to try `dual-publish` then and look forward to a future without CJS. Just to scratch a personal itch, I'll see if it's possible to publish for both CJS/ESM using just an npm script without an extra dev dep, but will merge here now. I'll go around publishing this tomorrow! :wave:

Thanks so much!

**Comment by jorgebucaran** [comment]
[`@1.2.1`](https://www.npmjs.com/package/colorette/v/1.2.1) should be now available with support for Node >= 8 and beyond. 🙌

**Pull request merged**
