### PR TITLE
feature: add rgb, ansi256, and ansi16 ANSI functions

### LINKED ISSUE #27: Support 8 & 24 bit color
https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

Additionally, generators for colors say,

`const mauve = colorette('#b784a7')`

Maybe theming too.

### PR DESCRIPTION
**Pull request by jorgebucaran**
Close #27

### CODE REVIEW

**Comment by AlisonVilelaTenchi** [comment]
Any news about this feature?

**Comment by jorgebucaran** [comment]
I want to focus on the core functionality of this package, and simply not address 8~24 bit color at this time.

**Comment by latuh** [comment]
3 years have passed, will this get done anytime soon?

**Comment by jorgebucaran** [comment]
[As previously stated](https://github.com/jorgebucaran/colorette/pull/29#issuecomment-786593712), I want to focus on the core functionality of this package, not 8-24 bit color. A closed PR should indicate that we are not planning to implement this feature. To be clear,  I have no plans to implement this feature now or likely ever (though never say never).

**Pull request closed without merging**
