### PR TITLE
fix: make sur it works in browser where tty package isnt available

### PR DESCRIPTION
**Pull request by WNemencha**

### CODE REVIEW

**Comment by jorgebucaran** [comment]
I'm curious. How are you using Colorette in the browser?

**Comment by WNemencha** [comment]
It's used in our dependencies by some tools (postcss i guess) and postcss is used by sanitize-html, which we do use to sanitize markdown ^^

**Comment by jorgebucaran** [comment]
Shouldn't this be handled by your bundler or compiler?

**Comment by kibertoad** [comment]
@jorgebucaran How can webpack handle Node context not being there?

**Comment by jorgebucaran** [comment]
I really don't know. What about a global shim? Colorette shouldn't be in the OP's bundle to start with. :trollface:

**Comment by kibertoad** [comment]
SSR is one possible option. Serverless is another.
I'm not sure there is a good working solution, and what is the issue with handling gracefully on colorette side? doesn't it come with zero performance impact?

**Comment by WNemencha** [comment]
Agree with @kibertoad, that's just a branch, and branches are cheap. Configuration of bundle processor in the other side isn't about branches, thus costly ^^

**Comment by kibertoad** [comment]
@WNemencha I wonder why additional check is necessary, though. Wouldn't tty be undefined already? Also is 'process' available? I would expect that to fail too.

**Comment by WNemencha** [comment]
@kibertoad tty from the import is undefined of course, the issue here is the `undefined.isatty()` call that obviously throws :(

**Comment by kibertoad** [comment]
@WNemencha Then `tty &&` part is completely useless and we should drop it.

**Comment by LeoniePhiline** [comment]
@WNemencha This is exactly https://github.com/jorgebucaran/colorette/issues/67

**Comment by jorgebucaran** [comment]
> @WNemencha Also, modern browsers supports process.browser...

Do you mean bundlers add special support for this? I'm not aware of any `process.browser` API in browsers or in node, is this an old thing? We are currently importing `process` explicitly, but maybe we don't have to?

**Pull request closed without merging**
