### PR TITLE
Request Feature: create a new feature to randomize the colors

### PR DESCRIPTION
**Pull request by edwinsamodra**
Hi! I have an idea that I think would be pretty good if it was in this repository. My idea is to create a function that is used to select a random color.

As we know, init() has two parameters. the first parameter refers to the color while the second parameter refers to the selection of background, text, or modifier
```
red: init(31, 39),
green: init(32, 39),
yellow: init(33, 39),
...
redBright: init(91, 39),
greenBright: init(92, 39),
yellowBright: init(93, 39),
```

Then I thought about how to create a variable value that can randomize a number pattern. Between 30 - 37 (Colors) and 90-97 (Bright Colors)

```
var randNum = Math.random() < 0.5
  ? Math.floor(Math.random() * ((37 + 1) - 30) + 30) // (Colors: 30 - 37)
  : Math.floor(Math.random() * ((97 + 1) - 90) + 90) // (Bright Colors: 90 - 97)
```

After that

`randColor: init(randNum, 39)`

And last

image

Please consider checking this one. Thanks

### CODE REVIEW

**Comment by kibertoad** [comment]
@edwinsamodra What is the use-case for this? Also can't this be implemented fairly easily in the userspace, picking from an array of colorizing methods randomly?

**Comment by edwinsamodra** [comment]
> @edwinsamodra What is the use-case for this? Also can't this be implemented fairly easily in the userspace, picking from an array of colorizing methods randomly?

Make it easy for users to create color variations.

**Comment by kibertoad** [comment]
@edwinsamodra That's description of a feature. Can you describe a real-world scenario when this functionality would be useful?

**Comment by afikrim** [comment]
I think it would be nice to have this function when I run out of colors.

For example, I have an application that have a lot of service, then I want to use my favorite colors for each service's log, and at some point I run out of colors to use, rather than search for a new color, I can use random function to generate some random colors in my log until I find the one that I like.

**Comment by kibertoad** [comment]
That sounds very niche and like something that belongs to a library dedicated to that end specifically. Considering that this is supposed to be a lightweight building block for other libraries, we generally tend to prefer avoiding non-essential features.

But it sounds like a cool idea for another lib, maybe you would like to create it?

**Comment by afikrim** [comment]
I'm sorry, I do not quite get what you mean by "maybe you would like to create it?". Do you ask me to make that thing in this library?

> That sounds very niche and like something that belongs to a library dedicated to that end specifically. Considering that this is supposed to be a lightweight building block for other libraries, we generally tend to prefer avoiding non-essential features.
> 
> But it sounds like a cool idea for another lib, maybe you would like to create it?

**Comment by adiatma85** [comment]
> I'm sorry, I do not quite get what you mean by "maybe you would like to create it?". Do you ask me to make that thing in this library?
> 
> > That sounds very niche and like something that belongs to a library dedicated to that end specifically. Considering that this is supposed to be a lightweight building block for other libraries, we generally tend to prefer avoiding non-essential features.
> > But it sounds like a cool idea for another lib, maybe you would like to create it?

I legitly think that you create another lib for that specific function.
I think your case is pretty similliar to what have I experienced, but as @kibertoad said, it's niche.
It's up to the owner to approve this or not, but the idea is really good overall

Cheers!

**Comment by jorgebucaran** [comment]
Thanks, @edwinsamodra! This would be nice, but not essential to have, so I'm afraid I'm going to pass. 

FYI, I'd implement it in userland like this.

```js
const createRandomColor = (...colors) =>
  colors[(colors.length * Math.random()) | 0]

const randomColor = createRandomColor([
  red,
  green,
  yellow,
  blue,
  magenta,
  cyan,
  white,
  gray
])

console.log(randomColor("<3"))
```

**Pull request closed without merging**
