### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by prantlf**
Build, test and benchmark work.

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Thank you, @prantlf! 💯

**Comment by prantlf** [comment]
You're welcome! :-)

Actually, I am sorry for realising too late that this change makes the tests fail on Node.js 8:

    > c8 testmatrix test/*.cjs

    .../colorette/node_modules/.pnpm/locate-path@6.0.0/node_modules/locate-path/index.js:41
    		} catch {
    		        ^
    SyntaxError: Unexpected token {

But nobody probably uses it any more.

I tested build, test and bench with v10.23.0, v12.20.0 and v14.15.1. The build on GitHub CI fails with an error, which I did noit encounter:

    > c8 testmatrix test/*.cjs

    internal/modules/cjs/loader.js:1080
          throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
          ^

    Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/colorette/colorette/index.js
    require() of ES modules is not supported.
    require() of /home/runner/work/colorette/colorette/index.js from /home/runner/work/colorette/colorette/test/index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
    Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/work/colorette/colorette/package.json.

        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)

**Comment by jorgebucaran** [comment]
@prantlf Is that because we upgraded `c8` too?

**Comment by prantlf** [comment]
Yes, for the first error. The newer `c8` requires apparently a supported LTS version. Node.js 8 reached its EOL. However, I cannot say if it affects `colorette`, which still might work.

I do not understand errors with other Node.js versions. They appear to be are independent on this change. My earlier PR got a failing build on the GitLab CI too failed too.

**Comment by jorgebucaran** [comment]
Seems like it's time to drop official Node 8 support then (it will still work, of course).

**Comment by prantlf** [comment]
@jorgebucaran, I installed v8.17.0 and I do not see the error either. I suspect that it is a problem specific to GitLab CI.

The only difference in the Node.js 8 output is the missing code coverage report at the end of `npm test`.

**Comment by jorgebucaran** [comment]
Thank you for checking @prantlf. I'll have a look as well tomorrow!

**Pull request merged**
